name: mesothelioma
channels:
  - conda-forge
dependencies:
  - geoplot=0.1.1
  - ipykernel=4.7.0
  - ipywidgets=7.0.5
  - matplotlib=2.1.1
  - notebook=5.2.2
  - pandas=0.21.1
  - python=3.6.3
  - requests=2.12.4
  - xlrd=1.1.0
  - pip:
    - quilt==2.8.0
